---
- name: forum | restart the forum service
  supervisorctl: >
    name=forum
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    state=restarted
  when: not forum_skip_supervisor
