browser_deb_pkgs:
    - xvfb
    - firefox
    - dbus-x11
    - libgconf2-4
    - libxss1
    - libnss3-1d
    - libcurl3
    - xdg-utils
    - google-chrome-stable

# Chrome and ChromeDriver
chrome_apt_key: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
chrome_apt_repo: "http://dl.google.com/linux/chrome/deb/"
chromedriver_version: 2.3
chromedriver_url: "http://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip"

browser_xvfb_display: ":1"
