---

- name: forum | test that the required service are listening
  wait_for: port={{ item.port }} host={{ item.host }} timeout=30
  with_items: "{{ forum_services }}"
  when: not forum_skip_supervisor
  tags:
  - forum
  - test
